# Generated by Django 4.1.4 on 2023-03-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='First_name',
            new_name='first_name',
        ),
    ]
